name: build_pkg

on:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@main
        with:
          pkgname: manjaro-chrootbuild
          repo: extra
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          branch: unstable
          
          # the following is only needed if non-standard
          # defaults source: https://gitlab.manjaro.org/packages/$repo/$pkgname.git
          source: https://gitlab.manjaro.org/tools/development-tools/manjaro-chrootbuild
