name: Build package

on:
  push:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@main
        with:
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
        
######### EDIT:
          package: manjaro-settings-manager
          repo: extra
          ## non-standard path to source repo - default: https://gitlab.manjaro.org/packages/$repo/$package
          source: 
          ## branch: (default: unstable)
          branch: unstable
          ## multilib: (default: false)
          multilib: false
          ## custom-repo - default: ""
          custom-repo: ""

# built Sat Oct 16 17:33:00 CEST 2021
