name: build_pkg

on:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@master
        with:
          pkgname: palemoon-bin
          repo: community
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          branch: unstable
