name: Build package

on:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@main
        with:
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
        
######### EDIT:
          pkgname: qt5-base
          repo: extra

######### OPTIONAL EDIT:
          ## non-standard source: (default: https://gitlab.manjaro.org/packages/$repo/$pkgname.git)
          # source: https://gitlab.manjaro.org/tools/development-tools/manjaro-chrootbuild
          ## branch: (default: unstable)
          branch: testing
