name: Build package

on:
  push:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@main
        with:
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
        
######### EDIT:
          package: manjaro-cli
          repo: community

######### OPTIONAL EDIT:
          ## non-standard source: (default: https://gitlab.manjaro.org/packages/$repo/$pkgname.git)
          # source: https://gitlab.manjaro.org/tools/development-tools/manjaro-chrootbuild
          ## branch: (default: unstable)
          # branch: testing
          ## multilib: (default: false)
          # multilib: true
          ## custom package: manjaro-cli
          # package: manjaro-cli
